// Catálogo de productos Hacendado con precios reales aproximados
// unidad_base: la unidad en la que se mide el producto internamente (g, ml, ud)
// cantidad_por_envase: cuántas unidades_base tiene el envase (ej: 1000g para 1kg)
// precio: precio del envase completo en euros

const productos = [
  // ────────────── FRUTAS Y VERDURAS ──────────────
  {
    nombre: 'Patatas Hacendado',
    categoria: 'Verduras',
    seccion_tienda: 'Frutas y Verduras',
    precio: 0.96,
    unidad_venta: '1 kg',
    cantidad_por_envase: 1000,
    unidad_base: 'g',
  },
  {
    nombre: 'Cebolla Hacendado',
    categoria: 'Verduras',
    seccion_tienda: 'Frutas y Verduras',
    precio: 0.79,
    unidad_venta: '1 kg',
    cantidad_por_envase: 1000,
    unidad_base: 'g',
  },
  {
    nombre: 'Tomate triturado Hacendado',
    categoria: 'Conservas',
    seccion_tienda: 'Aceites y Conservas',
    precio: 0.49,
    unidad_venta: '400 g',
    cantidad_por_envase: 400,
    unidad_base: 'g',
  },
  {
    nombre: 'Ajo en polvo Hacendado',
    categoria: 'Especias',
    seccion_tienda: 'Condimentos y Especias',
    precio: 0.85,
    unidad_venta: '80 g',
    cantidad_por_envase: 80,
    unidad_base: 'g',
  },
  {
    nombre: 'Pimiento rojo Hacendado',
    categoria: 'Verduras',
    seccion_tienda: 'Frutas y Verduras',
    precio: 1.20,
    unidad_venta: '1 kg',
    cantidad_por_envase: 1000,
    unidad_base: 'g',
  },
  {
    nombre: 'Zanahoria Hacendado',
    categoria: 'Verduras',
    seccion_tienda: 'Frutas y Verduras',
    precio: 0.69,
    unidad_venta: '1 kg',
    cantidad_por_envase: 1000,
    unidad_base: 'g',
  },
  {
    nombre: 'Espinacas frescas Hacendado',
    categoria: 'Verduras',
    seccion_tienda: 'Frutas y Verduras',
    precio: 1.09,
    unidad_venta: '300 g',
    cantidad_por_envase: 300,
    unidad_base: 'g',
  },
  {
    nombre: 'Limón Hacendado',
    categoria: 'Frutas',
    seccion_tienda: 'Frutas y Verduras',
    precio: 0.99,
    unidad_venta: '1 kg',
    cantidad_por_envase: 1000,
    unidad_base: 'g',
  },

  // ────────────── CARNES Y AVES ──────────────
  {
    nombre: 'Pechuga de pollo Hacendado',
    categoria: 'Aves',
    seccion_tienda: 'Carnes y Aves',
    precio: 3.95,
    unidad_venta: '1 kg',
    cantidad_por_envase: 1000,
    unidad_base: 'g',
  },
  {
    nombre: 'Carne picada mixta Hacendado',
    categoria: 'Carnes',
    seccion_tienda: 'Carnes y Aves',
    precio: 3.49,
    unidad_venta: '500 g',
    cantidad_por_envase: 500,
    unidad_base: 'g',
  },
  {
    nombre: 'Muslos de pollo Hacendado',
    categoria: 'Aves',
    seccion_tienda: 'Carnes y Aves',
    precio: 2.99,
    unidad_venta: '1 kg',
    cantidad_por_envase: 1000,
    unidad_base: 'g',
  },
  {
    nombre: 'Jamón serrano loncheado Hacendado',
    categoria: 'Embutidos',
    seccion_tienda: 'Carnes y Aves',
    precio: 1.49,
    unidad_venta: '100 g',
    cantidad_por_envase: 100,
    unidad_base: 'g',
  },

  // ────────────── PESCADOS Y MARISCOS ──────────────
  {
    nombre: 'Atún en aceite de oliva Hacendado',
    categoria: 'Conservas de pescado',
    seccion_tienda: 'Pescados y Mariscos',
    precio: 0.89,
    unidad_venta: '3 x 80 g',
    cantidad_por_envase: 240,
    unidad_base: 'g',
  },
  {
    nombre: 'Merluza congelada Hacendado',
    categoria: 'Pescado congelado',
    seccion_tienda: 'Congelados',
    precio: 4.99,
    unidad_venta: '500 g',
    cantidad_por_envase: 500,
    unidad_base: 'g',
  },

  // ────────────── LÁCTEOS Y HUEVOS ──────────────
  {
    nombre: 'Huevos Hacendado M',
    categoria: 'Huevos',
    seccion_tienda: 'Lácteos y Huevos',
    precio: 1.49,
    unidad_venta: '12 ud',
    cantidad_por_envase: 12,
    unidad_base: 'ud',
  },
  {
    nombre: 'Leche entera Hacendado',
    categoria: 'Leche',
    seccion_tienda: 'Lácteos y Huevos',
    precio: 0.68,
    unidad_venta: '1 L',
    cantidad_por_envase: 1000,
    unidad_base: 'ml',
  },
  {
    nombre: 'Mantequilla Hacendado',
    categoria: 'Mantequilla',
    seccion_tienda: 'Lácteos y Huevos',
    precio: 1.19,
    unidad_venta: '250 g',
    cantidad_por_envase: 250,
    unidad_base: 'g',
  },
  {
    nombre: 'Nata para cocinar Hacendado',
    categoria: 'Nata',
    seccion_tienda: 'Lácteos y Huevos',
    precio: 0.79,
    unidad_venta: '200 ml',
    cantidad_por_envase: 200,
    unidad_base: 'ml',
  },
  {
    nombre: 'Queso rallado Hacendado',
    categoria: 'Queso',
    seccion_tienda: 'Lácteos y Huevos',
    precio: 1.85,
    unidad_venta: '150 g',
    cantidad_por_envase: 150,
    unidad_base: 'g',
  },
  {
    nombre: 'Yogur natural Hacendado',
    categoria: 'Yogures',
    seccion_tienda: 'Lácteos y Huevos',
    precio: 0.75,
    unidad_venta: '4 x 125 g',
    cantidad_por_envase: 500,
    unidad_base: 'g',
  },

  // ────────────── PANADERÍA ──────────────
  {
    nombre: 'Pan de molde Hacendado',
    categoria: 'Pan',
    seccion_tienda: 'Panadería y Bollería',
    precio: 1.09,
    unidad_venta: '700 g',
    cantidad_por_envase: 700,
    unidad_base: 'g',
  },

  // ────────────── ACEITES Y CONSERVAS ──────────────
  {
    nombre: 'Aceite de oliva virgen extra Hacendado',
    categoria: 'Aceites',
    seccion_tienda: 'Aceites y Conservas',
    precio: 3.99,
    unidad_venta: '750 ml',
    cantidad_por_envase: 750,
    unidad_base: 'ml',
  },
  {
    nombre: 'Tomate frito Hacendado',
    categoria: 'Salsas',
    seccion_tienda: 'Aceites y Conservas',
    precio: 0.69,
    unidad_venta: '350 g',
    cantidad_por_envase: 350,
    unidad_base: 'g',
  },
  {
    nombre: 'Caldo de pollo Hacendado',
    categoria: 'Caldos',
    seccion_tienda: 'Aceites y Conservas',
    precio: 0.99,
    unidad_venta: '1 L',
    cantidad_por_envase: 1000,
    unidad_base: 'ml',
  },
  {
    nombre: 'Garbanzos cocidos Hacendado',
    categoria: 'Legumbres',
    seccion_tienda: 'Pasta, Arroz y Legumbres',
    precio: 0.79,
    unidad_venta: '400 g',
    cantidad_por_envase: 400,
    unidad_base: 'g',
  },

  // ────────────── PASTA, ARROZ Y LEGUMBRES ──────────────
  {
    nombre: 'Arroz redondo Hacendado',
    categoria: 'Arroz',
    seccion_tienda: 'Pasta, Arroz y Legumbres',
    precio: 0.89,
    unidad_venta: '1 kg',
    cantidad_por_envase: 1000,
    unidad_base: 'g',
  },
  {
    nombre: 'Espaguetis Hacendado',
    categoria: 'Pasta',
    seccion_tienda: 'Pasta, Arroz y Legumbres',
    precio: 0.59,
    unidad_venta: '500 g',
    cantidad_por_envase: 500,
    unidad_base: 'g',
  },
  {
    nombre: 'Macarrones Hacendado',
    categoria: 'Pasta',
    seccion_tienda: 'Pasta, Arroz y Legumbres',
    precio: 0.59,
    unidad_venta: '500 g',
    cantidad_por_envase: 500,
    unidad_base: 'g',
  },
  {
    nombre: 'Lentejas Hacendado',
    categoria: 'Legumbres',
    seccion_tienda: 'Pasta, Arroz y Legumbres',
    precio: 0.99,
    unidad_venta: '1 kg',
    cantidad_por_envase: 1000,
    unidad_base: 'g',
  },

  // ────────────── CONDIMENTOS Y ESPECIAS ──────────────
  {
    nombre: 'Sal marina Hacendado',
    categoria: 'Sal',
    seccion_tienda: 'Condimentos y Especias',
    precio: 0.39,
    unidad_venta: '1 kg',
    cantidad_por_envase: 1000,
    unidad_base: 'g',
  },
  {
    nombre: 'Pimienta negra molida Hacendado',
    categoria: 'Especias',
    seccion_tienda: 'Condimentos y Especias',
    precio: 0.79,
    unidad_venta: '50 g',
    cantidad_por_envase: 50,
    unidad_base: 'g',
  },
  {
    nombre: 'Pimentón dulce Hacendado',
    categoria: 'Especias',
    seccion_tienda: 'Condimentos y Especias',
    precio: 0.89,
    unidad_venta: '75 g',
    cantidad_por_envase: 75,
    unidad_base: 'g',
  },
  {
    nombre: 'Orégano Hacendado',
    categoria: 'Especias',
    seccion_tienda: 'Condimentos y Especias',
    precio: 0.59,
    unidad_venta: '15 g',
    cantidad_por_envase: 15,
    unidad_base: 'g',
  },
  {
    nombre: 'Harina de trigo Hacendado',
    categoria: 'Harinas',
    seccion_tienda: 'Pasta, Arroz y Legumbres',
    precio: 0.69,
    unidad_venta: '1 kg',
    cantidad_por_envase: 1000,
    unidad_base: 'g',
  },
];

module.exports = productos;
