// Seed de recetas con ingredientes mapeados a productos Hacendado reales
// Los nombres de producto en 'ingredientes' deben coincidir EXACTAMENTE
// con el campo 'nombre' del seed de productos.

const recetas = [
  {
    nombre: 'Arroz a la cubana exprés',
    descripcion: 'Una receta sencilla, económica y muy resultona. Arroz suelto, tomate caliente y huevo para una comida rápida de las que siempre funcionan.',
    foto_url: '/img/recetas/arroz_cubana.png',
    tiempo_minutos: 25,
    raciones_base: 2,
    semana_activa: '2026-06-02',
    dificultad: 'Fácil',
    categoria: 'Principal',
    calorias_racion: 520,
    autor_origen: 'Cocina Hacendado',
    cocina: 'Española',
    tags: ['VEGETARIANO', 'SIN_GLUTEN'],
    ingredientes: [
      { producto: 'Arroz redondo Hacendado', cantidad_base: 180, unidad: 'g', nombre_display: 'Arroz', grupo: 'Para el arroz' },
      { producto: 'Aceite de oliva virgen extra Hacendado', cantidad_base: 15, unidad: 'ml', nombre_display: 'Aceite', grupo: 'Para el arroz' },
      { producto: 'Sal marina Hacendado', cantidad_base: 3, unidad: 'g', nombre_display: 'Sal', grupo: 'Para el arroz' },
      { producto: 'Tomate frito Hacendado', cantidad_base: 200, unidad: 'g', nombre_display: 'Tomate frito', grupo: 'Para el tomate' },
      { producto: 'Huevos Hacendado M', cantidad_base: 2, unidad: 'ud', nombre_display: 'Huevos', grupo: 'Para el acabado' },
    ],
    pasos: [
      'Cuece el arroz en abundante agua con sal durante 16-18 minutos, hasta que quede tierno y suelto. Escurre y reserva.',
      'Calienta el tomate frito en un cazo pequeño a fuego suave durante 3-4 minutos, removiendo de vez en cuando.',
      'En una sartén antiadherente, calienta el aceite y fríe los huevos a fuego medio hasta que la clara esté cuajada y la yema siga melosa.',
      'Sirve el arroz en cada plato, añade el tomate caliente y termina con un huevo frito por ración.',
      'Ajusta de sal y sirve inmediatamente.',
    ],
    consejos: [
      'Para un arroz más suelto, enfríalo 2 minutos antes de servir.',
      'Si prefieres una versión ligera, usa huevo a la plancha en lugar de frito.',
    ],
    faq: [
      { pregunta: '¿Puedo usar arroz integral?', respuesta: 'Sí, pero aumenta el tiempo de cocción y ajusta la cantidad de agua.' },
      { pregunta: '¿Se puede preparar con antelación?', respuesta: 'Puedes dejar el arroz y el tomate listos; fríe el huevo al final.' },
    ],
    reviews: [
      { usuario: 'Laura M.', rating: 5, comentario: 'Clásico de toda la vida, rápido y rico.' },
      { usuario: 'Jorge R.', rating: 4, comentario: 'Muy resultón, con el tomate caliente queda perfecto.' },
    ],
  },
  {
    nombre: 'Merluza al horno con limón y patatas',
    descripcion: 'Una receta ligera y muy práctica para el día a día. La merluza se hornea con patatas, cebolla y limón para lograr un plato completo y limpio de sabores.',
    foto_url: '/img/recetas/merluza_horno.png',
    tiempo_minutos: 40,
    raciones_base: 4,
    semana_activa: '2026-06-02',
    dificultad: 'Fácil',
    categoria: 'Principal',
    calorias_racion: 430,
    autor_origen: 'Cocina Hacendado',
    cocina: 'Mediterránea',
    tags: ['SIN_GLUTEN', 'SIN_LACTOSA'],
    ingredientes: [
      { producto: 'Patatas Hacendado', cantidad_base: 500, unidad: 'g', nombre_display: 'Patatas', grupo: 'Para la base' },
      { producto: 'Cebolla Hacendado', cantidad_base: 120, unidad: 'g', nombre_display: 'Cebolla', grupo: 'Para la base' },
      { producto: 'Aceite de oliva virgen extra Hacendado', cantidad_base: 20, unidad: 'ml', nombre_display: 'Aceite', grupo: 'Para la base' },
      { producto: 'Sal marina Hacendado', cantidad_base: 3, unidad: 'g', nombre_display: 'Sal', grupo: 'Para la base' },
      { producto: 'Merluza congelada Hacendado', cantidad_base: 500, unidad: 'g', nombre_display: 'Merluza', grupo: 'Para el pescado' },
      { producto: 'Limón Hacendado', cantidad_base: 80, unidad: 'g', nombre_display: 'Limón', grupo: 'Para el pescado' },
      { producto: 'Pimienta negra molida Hacendado', cantidad_base: 2, unidad: 'g', nombre_display: 'Pimienta', grupo: 'Para el pescado' },
      { producto: 'Aceite de oliva virgen extra Hacendado', cantidad_base: 15, unidad: 'ml', nombre_display: 'Aceite', grupo: 'Para el pescado' },
    ],
    pasos: [
      'Precalienta el horno a 200°C. Pela las patatas y córtalas en rodajas finas. Corta la cebolla en juliana.',
      'Coloca patatas y cebolla en una bandeja de horno. Aliña con la mitad del aceite y una pizca de sal. Hornea 15 minutos para que se ablanden.',
      'Añade la merluza sobre la cama de verduras. Salpimenta, reparte el resto del aceite y coloca por encima unas rodajas finas de limón.',
      'Hornea 15-18 minutos más, hasta que la merluza esté tierna y jugosa.',
      'Sirve caliente con el jugo de la bandeja por encima.',
    ],
    consejos: [
      'Seca la merluza antes de hornear para que quede más firme.',
      'Añade perejil fresco al final para un toque más aromático.',
    ],
    faq: [
      { pregunta: '¿Puedo usar otro pescado blanco?', respuesta: 'Sí, bacalao fresco o lubina quedan perfectos con este método.' },
      { pregunta: '¿Se puede hacer con patata cocida?', respuesta: 'Sí, pero hornea menos tiempo para que no se deshaga.' },
    ],
    reviews: [
      { usuario: 'Ana L.', rating: 5, comentario: 'Fresco y ligero, el limón le da un toque genial.' },
      { usuario: 'Sergio P.', rating: 4, comentario: 'Muy fácil, ideal para cenas rápidas.' },
    ],
  },
  {
    nombre: 'Sopa rápida de pollo con arroz',
    descripcion: 'Reconfortante, fácil y perfecta para una comida ligera. El caldo, el arroz y el pollo hacen una sopa completa con sabor casero.',
    foto_url: '/img/recetas/sopa_pollo.png',
    tiempo_minutos: 30,
    raciones_base: 4,
    semana_activa: '2026-06-09',
    dificultad: 'Fácil',
    categoria: 'Entrante',
    calorias_racion: 360,
    autor_origen: 'Cocina Hacendado',
    cocina: 'Española',
    tags: ['SIN_GLUTEN', 'SIN_LACTOSA'],
    ingredientes: [
      { producto: 'Cebolla Hacendado', cantidad_base: 100, unidad: 'g', nombre_display: 'Cebolla', grupo: 'Para la base' },
      { producto: 'Zanahoria Hacendado', cantidad_base: 150, unidad: 'g', nombre_display: 'Zanahoria', grupo: 'Para la base' },
      { producto: 'Aceite de oliva virgen extra Hacendado', cantidad_base: 20, unidad: 'ml', nombre_display: 'Aceite', grupo: 'Para la base' },
      { producto: 'Pechuga de pollo Hacendado', cantidad_base: 400, unidad: 'g', nombre_display: 'Pechuga de pollo', grupo: 'Para la sopa' },
      { producto: 'Caldo de pollo Hacendado', cantidad_base: 1000, unidad: 'ml', nombre_display: 'Caldo de pollo', grupo: 'Para la sopa' },
      { producto: 'Arroz redondo Hacendado', cantidad_base: 120, unidad: 'g', nombre_display: 'Arroz', grupo: 'Para la sopa' },
      { producto: 'Sal marina Hacendado', cantidad_base: 4, unidad: 'g', nombre_display: 'Sal', grupo: 'Para la sopa' },
    ],
    pasos: [
      'Pica la cebolla y corta la zanahoria en dados pequeños. Trocea la pechuga de pollo en bocados pequeños.',
      'Sofríe la cebolla y la zanahoria con el aceite en una olla durante 6-7 minutos a fuego medio.',
      'Añade el pollo y rehógalo 3 minutos hasta que cambie de color.',
      'Vierte el caldo, lleva a ebullición y añade el arroz. Sala ligeramente.',
      'Cuece 16-18 minutos a fuego medio hasta que el arroz esté tierno. Ajusta de sal y sirve muy caliente.',
    ],
    consejos: [
      'Si quieres más cuerpo, añade un poco más de arroz al final.',
      'Unas gotas de limón levantan el sabor del caldo.',
    ],
    faq: [
      { pregunta: '¿Se puede congelar?', respuesta: 'Sí, pero el arroz puede absorber caldo; añade un poco al recalentar.' },
      { pregunta: '¿Puedo usar pollo asado?', respuesta: 'Sí, incorpóralo al final para que no se seque.' },
    ],
    reviews: [
      { usuario: 'Paula G.', rating: 5, comentario: 'Reconfortante y muy fácil.' },
      { usuario: 'Mario F.', rating: 4, comentario: 'Perfecta para cuando no tienes tiempo.' },
    ],
  },
  {
    nombre: 'Ensalada templada de garbanzos y atún',
    descripcion: 'Una receta muy completa y rápida para comer bien sin complicarse. Combina legumbre, proteína y un aliño sencillo de limón y aceite.',
    foto_url: '/img/recetas/ensalada_garbanzos.png',
    tiempo_minutos: 12,
    raciones_base: 2,
    semana_activa: '2026-06-09',
    dificultad: 'Fácil',
    categoria: 'Entrante',
    calorias_racion: 420,
    autor_origen: 'Cocina Hacendado',
    cocina: 'Mediterránea',
    tags: ['SIN_GLUTEN', 'SIN_LACTOSA'],
    ingredientes: [
      { producto: 'Garbanzos cocidos Hacendado', cantidad_base: 400, unidad: 'g', nombre_display: 'Garbanzos', grupo: 'Para la ensalada' },
      { producto: 'Atún en aceite de oliva Hacendado', cantidad_base: 240, unidad: 'g', nombre_display: 'Atún', grupo: 'Para la ensalada' },
      { producto: 'Pimiento rojo Hacendado', cantidad_base: 120, unidad: 'g', nombre_display: 'Pimiento rojo', grupo: 'Para la ensalada' },
      { producto: 'Cebolla Hacendado', cantidad_base: 60, unidad: 'g', nombre_display: 'Cebolla', grupo: 'Para la ensalada' },
      { producto: 'Limón Hacendado', cantidad_base: 50, unidad: 'g', nombre_display: 'Limón', grupo: 'Para el aliño' },
      { producto: 'Aceite de oliva virgen extra Hacendado', cantidad_base: 20, unidad: 'ml', nombre_display: 'Aceite', grupo: 'Para el aliño' },
      { producto: 'Sal marina Hacendado', cantidad_base: 3, unidad: 'g', nombre_display: 'Sal', grupo: 'Para el aliño' },
    ],
    pasos: [
      'Escurre y enjuaga bien los garbanzos. Escurre también el atún.',
      'Corta el pimiento y la cebolla en dados pequeños.',
      'Templa los garbanzos 2 minutos en una sartén o en el microondas para que la ensalada quede más agradable.',
      'Mezcla en un bol grande los garbanzos, el atún, el pimiento y la cebolla.',
      'Aliña con zumo de limón, aceite y sal. Remueve con suavidad y sirve al momento.',
    ],
    consejos: [
      'Si quieres más frescor, añade un toque de perejil picado.',
      'Para un extra de proteína, añade un huevo duro picado.',
    ],
    faq: [
      { pregunta: '¿Se puede tomar fría?', respuesta: 'Sí, queda muy bien refrigerada y con un poco más de limón.' },
      { pregunta: '¿Puedo cambiar el atún?', respuesta: 'Puedes usar caballa o bonito en conserva.' },
    ],
    reviews: [
      { usuario: 'Irene S.', rating: 5, comentario: 'Rápida y saciante, ideal para tupper.' },
      { usuario: 'Carlos V.', rating: 4, comentario: 'El aliño de limón le queda genial.' },
    ],
  },
  {
    nombre: 'Tostas gratinadas de jamón y queso',
    descripcion: 'Crujientes, sabrosas y listas en muy poco tiempo. Perfectas para una cena rápida, un picoteo o una comida informal de fin de semana.',
    foto_url: '/img/recetas/tostas_jamon_queso.png',
    tiempo_minutos: 15,
    raciones_base: 2,
    semana_activa: '2026-06-16',
    dificultad: 'Fácil',
    categoria: 'Desayuno/Merienda',
    calorias_racion: 540,
    autor_origen: 'Cocina Hacendado',
    cocina: 'Española',
    tags: [],
    ingredientes: [
      { producto: 'Pan de molde Hacendado', cantidad_base: 240, unidad: 'g', nombre_display: 'Pan de molde', grupo: 'Para las tostas' },
      { producto: 'Tomate frito Hacendado', cantidad_base: 120, unidad: 'g', nombre_display: 'Tomate frito', grupo: 'Para las tostas' },
      { producto: 'Jamón serrano loncheado Hacendado', cantidad_base: 80, unidad: 'g', nombre_display: 'Jamón serrano', grupo: 'Para las tostas' },
      { producto: 'Queso rallado Hacendado', cantidad_base: 120, unidad: 'g', nombre_display: 'Queso rallado', grupo: 'Para el gratinado' },
      { producto: 'Orégano Hacendado', cantidad_base: 2, unidad: 'g', nombre_display: 'Orégano', grupo: 'Para el gratinado' },
      { producto: 'Aceite de oliva virgen extra Hacendado', cantidad_base: 10, unidad: 'ml', nombre_display: 'Aceite', grupo: 'Para el acabado' },
    ],
    pasos: [
      'Precalienta el horno a 220°C o enciende el grill.',
      'Coloca las rebanadas de pan sobre una bandeja. Unta cada una con una fina capa de tomate frito.',
      'Reparte el jamón serrano por encima y añade el queso rallado.',
      'Riega con un hilo fino de aceite y espolvorea orégano al gusto.',
      'Gratina 5-7 minutos hasta que el queso se funda y empiece a dorarse. Sirve enseguida.',
    ],
    consejos: [
      'Si quieres más crujiente, tuesta el pan 2 minutos antes de montar.',
      'Un toque de pimienta recién molida realza el queso.',
    ],
    faq: [
      { pregunta: '¿Puedo usar otro pan?', respuesta: 'Sí, el pan rústico queda genial para un acabado más gourmet.' },
      { pregunta: '¿Se puede preparar con antelación?', respuesta: 'Monta las tostas y gratina justo antes de servir.' },
    ],
    reviews: [
      { usuario: 'Rocio D.', rating: 5, comentario: 'Súper rápidas y con mucho sabor.' },
      { usuario: 'Diego N.', rating: 4, comentario: 'Perfectas para una cena informal.' },
    ],
  },
  {
    nombre: 'Espaguetis con atún y tomate',
    descripcion: 'Una receta sencilla, marinera y muy apañada para diario. La salsa de tomate con atún funciona especialmente bien con pasta larga y queda lista en poco tiempo.',
    foto_url: '/img/recetas/espaguetis_atun.png',
    tiempo_minutos: 20,
    raciones_base: 4,
    semana_activa: '2026-06-16',
    dificultad: 'Fácil',
    categoria: 'Principal',
    calorias_racion: 580,
    autor_origen: 'Cocina Hacendado',
    cocina: 'Italiana',
    tags: ['SIN_LACTOSA'],
    ingredientes: [
      { producto: 'Espaguetis Hacendado', cantidad_base: 320, unidad: 'g', nombre_display: 'Espaguetis', grupo: 'Para la pasta' },
      { producto: 'Sal marina Hacendado', cantidad_base: 4, unidad: 'g', nombre_display: 'Sal', grupo: 'Para la pasta' },
      { producto: 'Cebolla Hacendado', cantidad_base: 80, unidad: 'g', nombre_display: 'Cebolla', grupo: 'Para la salsa' },
      { producto: 'Tomate frito Hacendado', cantidad_base: 300, unidad: 'g', nombre_display: 'Tomate frito', grupo: 'Para la salsa' },
      { producto: 'Atún en aceite de oliva Hacendado', cantidad_base: 240, unidad: 'g', nombre_display: 'Atún', grupo: 'Para la salsa' },
      { producto: 'Orégano Hacendado', cantidad_base: 2, unidad: 'g', nombre_display: 'Orégano', grupo: 'Para la salsa' },
      { producto: 'Aceite de oliva virgen extra Hacendado', cantidad_base: 20, unidad: 'ml', nombre_display: 'Aceite', grupo: 'Para la salsa' },
    ],
    pasos: [
      'Cuece los espaguetis en abundante agua con sal siguiendo el tiempo del envase. Escúrrelos al dente.',
      'Mientras tanto, sofríe la cebolla picada con el aceite durante 6-7 minutos a fuego medio.',
      'Añade el tomate frito y el orégano. Cocina 3 minutos para que la salsa coja cuerpo.',
      'Incorpora el atún escurrido y mezcla con suavidad durante 1-2 minutos.',
      'Añade los espaguetis a la sartén, mezcla bien para que se impregnen de la salsa y sirve al momento.',
    ],
    consejos: [
      'Reserva un poco de agua de cocción para aligerar la salsa si hace falta.',
      'Si te gusta picante, añade una pizca de guindilla.',
    ],
    faq: [
      { pregunta: '¿Se puede usar tomate triturado?', respuesta: 'Sí, sofríelo un poco más para concentrar el sabor.' },
      { pregunta: '¿Puedo usar pasta integral?', respuesta: 'Sí, ajusta el tiempo de cocción según el paquete.' },
    ],
    reviews: [
      { usuario: 'Nerea J.', rating: 5, comentario: 'Salsa rápida y muy sabrosa.' },
      { usuario: 'Adrian K.', rating: 4, comentario: 'Ideal para diario, se hace en 20 minutos.' },
    ],
  },
  {
    nombre: 'Lentejas melosas con arroz y pimentón',
    descripcion: 'Una receta humilde y muy completa, con cuchara y sabor de diario. El arroz le da cuerpo al guiso y el pimentón aporta un fondo muy casero.',
    foto_url: '/img/recetas/lentejas_arroz.png',
    tiempo_minutos: 40,
    raciones_base: 4,
    semana_activa: '2026-06-23',
    dificultad: 'Media',
    categoria: 'Principal',
    calorias_racion: 480,
    autor_origen: 'Cocina Hacendado',
    cocina: 'Española',
    tags: ['VEGANO', 'VEGETARIANO', 'SIN_GLUTEN', 'SIN_LACTOSA', 'SIN_HUEVO'],
    ingredientes: [
      { producto: 'Cebolla Hacendado', cantidad_base: 120, unidad: 'g', nombre_display: 'Cebolla', grupo: 'Para el sofrito' },
      { producto: 'Zanahoria Hacendado', cantidad_base: 150, unidad: 'g', nombre_display: 'Zanahoria', grupo: 'Para el sofrito' },
      { producto: 'Pimiento rojo Hacendado', cantidad_base: 100, unidad: 'g', nombre_display: 'Pimiento rojo', grupo: 'Para el sofrito' },
      { producto: 'Aceite de oliva virgen extra Hacendado', cantidad_base: 30, unidad: 'ml', nombre_display: 'Aceite', grupo: 'Para el sofrito' },
      { producto: 'Pimentón dulce Hacendado', cantidad_base: 5, unidad: 'g', nombre_display: 'Pimentón dulce', grupo: 'Para el sofrito' },
      { producto: 'Lentejas Hacendado', cantidad_base: 320, unidad: 'g', nombre_display: 'Lentejas', grupo: 'Para el guiso' },
      { producto: 'Arroz redondo Hacendado', cantidad_base: 120, unidad: 'g', nombre_display: 'Arroz', grupo: 'Para el guiso' },
      { producto: 'Sal marina Hacendado', cantidad_base: 5, unidad: 'g', nombre_display: 'Sal', grupo: 'Para el guiso' },
    ],
    pasos: [
      'Pica la cebolla, la zanahoria y el pimiento en dados pequeños.',
      'Sofríe las verduras con el aceite durante 8-10 minutos a fuego medio.',
      'Añade el pimentón dulce y remueve unos segundos para que perfume el sofrito.',
      'Incorpora las lentejas y cúbrelas con agua abundante. Cocina 20 minutos a fuego medio.',
      'Añade el arroz, ajusta de sal y cocina 15-18 minutos más hasta que el conjunto quede meloso. Sirve caliente.',
    ],
    consejos: [
      'Si quieres más caldo, añade agua caliente durante la cocción final.',
      'Deja reposar 5 minutos para que el arroz termine de integrar el caldo.',
    ],
    faq: [
      { pregunta: '¿Se puede hacer con lenteja pardina?', respuesta: 'Sí, reduce ligeramente el tiempo de cocción.' },
      { pregunta: '¿Queda bien para congelar?', respuesta: 'Sí, congela en porciones y descongela lentamente.' },
    ],
    reviews: [
      { usuario: 'Sonia T.', rating: 5, comentario: 'Muy melosas y con sabor casero.' },
      { usuario: 'Alex B.', rating: 4, comentario: 'Se queda perfecta con el toque de pimentón.' },
    ],
  },
  {
    nombre: 'Pollo salteado con espinacas y arroz',
    descripcion: 'Un plato completo, rápido y con perfil muy de diario. El pollo se saltea con cebolla y espinacas y se sirve con arroz para una comida redonda.',
    foto_url: '/img/recetas/pollo_espinacas.png',
    tiempo_minutos: 30,
    raciones_base: 4,
    semana_activa: '2026-06-23',
    dificultad: 'Fácil',
    categoria: 'Principal',
    calorias_racion: 520,
    autor_origen: 'Cocina Hacendado',
    cocina: 'Española',
    tags: ['SIN_GLUTEN', 'SIN_LACTOSA'],
    ingredientes: [
      { producto: 'Arroz redondo Hacendado', cantidad_base: 250, unidad: 'g', nombre_display: 'Arroz', grupo: 'Para el arroz' },
      { producto: 'Sal marina Hacendado', cantidad_base: 3, unidad: 'g', nombre_display: 'Sal', grupo: 'Para el arroz' },
      { producto: 'Pechuga de pollo Hacendado', cantidad_base: 700, unidad: 'g', nombre_display: 'Pechuga de pollo', grupo: 'Para el salteado' },
      { producto: 'Espinacas frescas Hacendado', cantidad_base: 200, unidad: 'g', nombre_display: 'Espinacas', grupo: 'Para el salteado' },
      { producto: 'Cebolla Hacendado', cantidad_base: 120, unidad: 'g', nombre_display: 'Cebolla', grupo: 'Para el salteado' },
      { producto: 'Ajo en polvo Hacendado', cantidad_base: 4, unidad: 'g', nombre_display: 'Ajo en polvo', grupo: 'Para el salteado' },
      { producto: 'Aceite de oliva virgen extra Hacendado', cantidad_base: 30, unidad: 'ml', nombre_display: 'Aceite', grupo: 'Para el salteado' },
      { producto: 'Pimienta negra molida Hacendado', cantidad_base: 2, unidad: 'g', nombre_display: 'Pimienta', grupo: 'Para el salteado' },
    ],
    pasos: [
      'Cuece el arroz en agua con sal hasta que esté en su punto. Escurre y reserva.',
      'Corta la pechuga en tiras y salpiméntala con el ajo en polvo.',
      'Sofríe la cebolla en una sartén amplia con el aceite durante 5-6 minutos.',
      'Añade el pollo y saltéalo a fuego vivo hasta que se dore y quede bien hecho.',
      'Incorpora las espinacas, cocina 2-3 minutos hasta que bajen de volumen y sirve junto al arroz.',
    ],
    consejos: [
      'Corta el pollo en tiras finas para que se haga en menos tiempo.',
      'Puedes añadir un toque de limón al final para dar frescor.',
    ],
    faq: [
      { pregunta: '¿Se puede usar arroz basmati?', respuesta: 'Sí, aporta un aroma más ligero.' },
      { pregunta: '¿Y si no tengo espinacas frescas?', respuesta: 'Puedes usar espinacas congeladas bien escurridas.' },
    ],
    reviews: [
      { usuario: 'Helena P.', rating: 5, comentario: 'Muy equilibrado y fácil.' },
      { usuario: 'Luis A.', rating: 4, comentario: 'Queda jugoso y con buen sabor.' },
    ],
  },
  {
    nombre: 'Macarrones cremosos con nata y queso',
    descripcion: 'Cremosos, suaves y muy resultones para una comida rápida. La nata y el queso envuelven la pasta en una salsa sencilla y muy apetecible.',
    foto_url: '/img/recetas/macarrones_queso.png',
    tiempo_minutos: 25,
    raciones_base: 4,
    semana_activa: '2026-06-30',
    dificultad: 'Fácil',
    categoria: 'Principal',
    calorias_racion: 650,
    autor_origen: 'Cocina Hacendado',
    cocina: 'Italiana',
    tags: ['VEGETARIANO'],
    ingredientes: [
      { producto: 'Macarrones Hacendado', cantidad_base: 350, unidad: 'g', nombre_display: 'Macarrones', grupo: 'Para la pasta' },
      { producto: 'Sal marina Hacendado', cantidad_base: 3, unidad: 'g', nombre_display: 'Sal', grupo: 'Para la pasta' },
      { producto: 'Cebolla Hacendado', cantidad_base: 80, unidad: 'g', nombre_display: 'Cebolla', grupo: 'Para la salsa' },
      { producto: 'Nata para cocinar Hacendado', cantidad_base: 200, unidad: 'ml', nombre_display: 'Nata para cocinar', grupo: 'Para la salsa' },
      { producto: 'Queso rallado Hacendado', cantidad_base: 120, unidad: 'g', nombre_display: 'Queso rallado', grupo: 'Para la salsa' },
      { producto: 'Aceite de oliva virgen extra Hacendado', cantidad_base: 20, unidad: 'ml', nombre_display: 'Aceite', grupo: 'Para la salsa' },
      { producto: 'Pimienta negra molida Hacendado', cantidad_base: 2, unidad: 'g', nombre_display: 'Pimienta', grupo: 'Para la salsa' },
    ],
    pasos: [
      'Cuece los macarrones en abundante agua con sal hasta que queden al dente. Escurre y reserva.',
      'Sofríe la cebolla muy picada con el aceite durante 5 minutos a fuego medio.',
      'Añade la nata, la sal y la pimienta. Cocina 2 minutos hasta que empiece a espesar.',
      'Incorpora el queso rallado y remueve hasta que se funda por completo.',
      'Añade la pasta, mezcla bien para que quede impregnada de la salsa y sirve enseguida.',
    ],
    consejos: [
      'Si quieres un gratinado rápido, añade queso extra y gratina 3 minutos.',
      'Un poco de orégano seco combina muy bien con esta salsa.',
    ],
    faq: [
      { pregunta: '¿Se puede usar otra pasta?', respuesta: 'Sí, penne o espirales funcionan igual de bien.' },
      { pregunta: '¿Puedo hacerla sin cebolla?', respuesta: 'Sí, pero añade un poco más de queso para dar cuerpo.' },
    ],
    reviews: [
      { usuario: 'Diana C.', rating: 5, comentario: 'Muy cremosa y reconfortante.' },
      { usuario: 'Rafa V.', rating: 4, comentario: 'Receta fácil para toda la familia.' },
    ],
  },
  {
    nombre: 'Tortilla campera rápida',
    descripcion: 'Una tortilla jugosa y sencilla con patata, cebolla y pimiento rojo. Tiene un punto más completo que la francesa, pero sigue siendo muy rápida de preparar.',
    foto_url: '/img/recetas/tortilla_campera.png',
    tiempo_minutos: 30,
    raciones_base: 3,
    semana_activa: '2026-06-30',
    dificultad: 'Media',
    categoria: 'Principal',
    calorias_racion: 460,
    autor_origen: 'Cocina Hacendado',
    cocina: 'Española',
    tags: ['SIN_GLUTEN'],
    ingredientes: [
      { producto: 'Patatas Hacendado', cantidad_base: 400, unidad: 'g', nombre_display: 'Patatas', grupo: 'Para la base' },
      { producto: 'Cebolla Hacendado', cantidad_base: 100, unidad: 'g', nombre_display: 'Cebolla', grupo: 'Para la base' },
      { producto: 'Pimiento rojo Hacendado', cantidad_base: 100, unidad: 'g', nombre_display: 'Pimiento rojo', grupo: 'Para la base' },
      { producto: 'Aceite de oliva virgen extra Hacendado', cantidad_base: 60, unidad: 'ml', nombre_display: 'Aceite', grupo: 'Para la base' },
      { producto: 'Huevos Hacendado M', cantidad_base: 5, unidad: 'ud', nombre_display: 'Huevos', grupo: 'Para el cuajado' },
      { producto: 'Sal marina Hacendado', cantidad_base: 4, unidad: 'g', nombre_display: 'Sal', grupo: 'Para el cuajado' },
    ],
    pasos: [
      'Pela las patatas y córtalas en dados pequeños. Pica la cebolla y el pimiento.',
      'Fríe patata, cebolla y pimiento con el aceite a fuego medio durante 12-15 minutos hasta que estén tiernos.',
      'Escurre el exceso de aceite y mezcla las verduras con los huevos batidos y la sal.',
      'Vierte la mezcla en una sartén antiadherente y cuaja la tortilla 2-3 minutos por cada lado.',
      'Sirve caliente o templada, recién hecha.',
    ],
    consejos: [
      'Si te gusta más jugosa, baja el fuego y cuaja menos tiempo.',
      'Deja reposar 2 minutos antes de cortar para que asiente.',
    ],
    faq: [
      { pregunta: '¿Puedo hacerla sin pimiento?', respuesta: 'Sí, queda más clásica pero igual de rica.' },
      { pregunta: '¿Se puede hacer al horno?', respuesta: 'Sí, hornea a 190°C unos 18-20 minutos.' },
    ],
    reviews: [
      { usuario: 'Eva M.', rating: 5, comentario: 'Textura perfecta y muy sabrosa.' },
      { usuario: 'Pablo S.', rating: 4, comentario: 'Me gusta el toque del pimiento.' },
    ],
  },
  {
    nombre: 'Lasaña suave de pollo y espinacas',
    descripcion: 'Capas finas de pasta, relleno jugoso y bechamel cremosa. Un clásico italiano con toque suave y muy familiar.',
    foto_url: '/img/recetas/lasana_pollo_espinacas.png',
    tiempo_minutos: 55,
    raciones_base: 4,
    semana_activa: '2026-07-07',
    dificultad: 'Difícil',
    categoria: 'Principal',
    calorias_racion: 690,
    autor_origen: 'Cocina Hacendado',
    cocina: 'Italiana',
    tags: [],
    ingredientes: [
      { producto: 'Pechuga de pollo Hacendado', cantidad_base: 450, unidad: 'g', nombre_display: 'Pollo', grupo: 'Para el relleno' },
      { producto: 'Espinacas frescas Hacendado', cantidad_base: 200, unidad: 'g', nombre_display: 'Espinacas', grupo: 'Para el relleno' },
      { producto: 'Cebolla Hacendado', cantidad_base: 120, unidad: 'g', nombre_display: 'Cebolla', grupo: 'Para el relleno' },
      { producto: 'Tomate triturado Hacendado', cantidad_base: 300, unidad: 'g', nombre_display: 'Tomate triturado', grupo: 'Para el relleno' },
      { producto: 'Aceite de oliva virgen extra Hacendado', cantidad_base: 25, unidad: 'ml', nombre_display: 'Aceite', grupo: 'Para el relleno' },
      { producto: 'Sal marina Hacendado', cantidad_base: 4, unidad: 'g', nombre_display: 'Sal', grupo: 'Para el relleno' },
      { producto: 'Pimienta negra molida Hacendado', cantidad_base: 2, unidad: 'g', nombre_display: 'Pimienta', grupo: 'Para el relleno' },
      { producto: 'Leche entera Hacendado', cantidad_base: 700, unidad: 'ml', nombre_display: 'Leche', grupo: 'Para la bechamel' },
      { producto: 'Harina de trigo Hacendado', cantidad_base: 50, unidad: 'g', nombre_display: 'Harina', grupo: 'Para la bechamel' },
      { producto: 'Mantequilla Hacendado', cantidad_base: 40, unidad: 'g', nombre_display: 'Mantequilla', grupo: 'Para la bechamel' },
      { producto: 'Sal marina Hacendado', cantidad_base: 2, unidad: 'g', nombre_display: 'Sal', grupo: 'Para la bechamel' },
      { producto: 'Pimienta negra molida Hacendado', cantidad_base: 1, unidad: 'g', nombre_display: 'Pimienta', grupo: 'Para la bechamel' },
      { producto: 'Láminas de lasaña Hacendado', cantidad_base: 200, unidad: 'g', nombre_display: 'Láminas de lasaña', grupo: 'Para el montaje' },
      { producto: 'Queso rallado Hacendado', cantidad_base: 120, unidad: 'g', nombre_display: 'Queso rallado', grupo: 'Para el montaje' },
      { producto: 'Mozzarella rallada Hacendado', cantidad_base: 80, unidad: 'g', nombre_display: 'Mozzarella', grupo: 'Para el montaje' },
    ],
    pasos: [
      'Sofríe la cebolla con el aceite 6 minutos. Añade el pollo picado y dora 5 minutos.',
      'Incorpora las espinacas y el tomate triturado. Cocina 8 minutos y ajusta de sal y pimienta.',
      'Para la bechamel, derrite la mantequilla, añade la harina y cocina 1 minuto. Vierte la leche poco a poco sin dejar de remover.',
      'Cocina la bechamel hasta que espese. Salpimenta al gusto.',
      'Monta la lasaña alternando capas de pasta, relleno y bechamel. Termina con queso rallado y mozzarella.',
      'Hornea a 200°C durante 18-20 minutos, hasta dorar la superficie. Deja reposar 5 minutos y sirve.',
    ],
    consejos: [
      'Si la bechamel queda muy espesa, añade un poco más de leche caliente.',
      'Deja reposar la lasaña antes de cortar para que mantenga la forma.',
    ],
    faq: [
      { pregunta: '¿Se puede preparar con antelación?', respuesta: 'Sí, monta y guarda en frío; hornea justo antes de servir.' },
      { pregunta: '¿Puedo usar espinacas congeladas?', respuesta: 'Sí, escúrrelas bien para evitar exceso de agua.' },
    ],
    reviews: [
      { usuario: 'Claudia H.', rating: 5, comentario: 'Muy cremosa y con capas perfectas.' },
      { usuario: 'Julio R.', rating: 4, comentario: 'Sabe muy casera, repetiré.' },
    ],
  },
  {
    nombre: 'Salsa de tomate casera al punto',
    descripcion: 'Una salsa base versátil para pasta, arroz o tostadas. Sabor limpio, textura suave y perfecta para batch cooking.',
    foto_url: '/img/recetas/salsa_tomate.png',
    tiempo_minutos: 25,
    raciones_base: 4,
    semana_activa: '2026-07-14',
    dificultad: 'Fácil',
    categoria: 'Salsa/Acompañamiento',
    calorias_racion: 120,
    autor_origen: 'Cocina Hacendado',
    cocina: 'Italiana',
    tags: ['VEGANO', 'VEGETARIANO', 'SIN_GLUTEN', 'SIN_LACTOSA', 'SIN_HUEVO'],
    ingredientes: [
      { producto: 'Aceite de oliva virgen extra Hacendado', cantidad_base: 25, unidad: 'ml', nombre_display: 'Aceite de oliva', grupo: 'Para la base' },
      { producto: 'Cebolla Hacendado', cantidad_base: 120, unidad: 'g', nombre_display: 'Cebolla', grupo: 'Para la base' },
      { producto: 'Tomate triturado Hacendado', cantidad_base: 600, unidad: 'g', nombre_display: 'Tomate triturado', grupo: 'Para la salsa' },
      { producto: 'Sal marina Hacendado', cantidad_base: 4, unidad: 'g', nombre_display: 'Sal', grupo: 'Para la salsa' },
      { producto: 'Orégano Hacendado', cantidad_base: 2, unidad: 'g', nombre_display: 'Orégano', grupo: 'Para la salsa' },
    ],
    pasos: [
      'Sofríe la cebolla con el aceite durante 7-8 minutos hasta que quede transparente.',
      'Añade el tomate triturado y la sal. Cocina a fuego medio 12-15 minutos, removiendo a menudo.',
      'Incorpora el orégano en los últimos 2 minutos para que perfume sin amargar.',
      'Si quieres una textura más fina, tritura ligeramente la salsa.',
      'Deja reposar 5 minutos antes de servir o guardar.',
    ],
    consejos: [
      'Si la salsa está ácida, añade una pizca de azúcar para equilibrar.',
      'Guárdala en frío hasta 3 días o congélala en porciones.',
    ],
    faq: [
      { pregunta: '¿Se puede usar tomate frito?', respuesta: 'Sí, pero reduce el tiempo de cocción a 6-8 minutos.' },
      { pregunta: '¿Puedo añadir ajo?', respuesta: 'Sí, sofríe un diente junto a la cebolla para más aroma.' },
    ],
    reviews: [
      { usuario: 'Lucia M.', rating: 5, comentario: 'Base perfecta para pasta y pizza rápida.' },
      { usuario: 'Gonzalo R.', rating: 4, comentario: 'Sabor limpio y fácil de hacer.' },
    ],
  },
  {
    nombre: 'Bizcocho de yogur y limón',
    descripcion: 'Bizcocho esponjoso con aroma cítrico. Ideal para desayunos y meriendas con un toque casero y suave.',
    foto_url: '/img/recetas/bizcocho_yogur.png',
    tiempo_minutos: 50,
    raciones_base: 8,
    semana_activa: '2026-07-14',
    dificultad: 'Media',
    categoria: 'Postre',
    calorias_racion: 310,
    autor_origen: 'Cocina Hacendado',
    cocina: 'Mediterránea',
    tags: ['VEGETARIANO'],
    ingredientes: [
      { producto: 'Yogur natural Hacendado', cantidad_base: 125, unidad: 'g', nombre_display: 'Yogur natural', grupo: 'Para la masa' },
      { producto: 'Huevos Hacendado M', cantidad_base: 3, unidad: 'ud', nombre_display: 'Huevos', grupo: 'Para la masa' },
      { producto: 'Azúcar blanco Hacendado', cantidad_base: 180, unidad: 'g', nombre_display: 'Azúcar', grupo: 'Para la masa' },
      { producto: 'Harina de trigo Hacendado', cantidad_base: 200, unidad: 'g', nombre_display: 'Harina', grupo: 'Para la masa' },
      { producto: 'Aceite de oliva suave Hacendado', cantidad_base: 80, unidad: 'ml', nombre_display: 'Aceite', grupo: 'Para la masa' },
      { producto: 'Levadura química Hacendado', cantidad_base: 10, unidad: 'g', nombre_display: 'Levadura química', grupo: 'Para la masa' },
      { producto: 'Limón Hacendado', cantidad_base: 20, unidad: 'g', nombre_display: 'Ralladura de limón', grupo: 'Para el aroma' },
    ],
    pasos: [
      'Precalienta el horno a 180°C y engrasa un molde de 20-22 cm.',
      'Bate los huevos con el azúcar hasta que la mezcla blanquee.',
      'Añade el yogur, el aceite y la ralladura de limón. Mezcla bien.',
      'Incorpora la harina con la levadura tamizadas y mezcla hasta integrar.',
      'Vierte la masa en el molde y hornea 30-35 minutos, hasta que salga limpio el palillo.',
      'Deja templar 10 minutos antes de desmoldar.',
    ],
    consejos: [
      'Si lo quieres más jugoso, añade un chorrito de limón al final.',
      'Guárdalo envuelto para que mantenga la humedad.',
    ],
    faq: [
      { pregunta: '¿Puedo usar leche en lugar de yogur?', respuesta: 'Sí, pero perderá parte de la esponjosidad.' },
      { pregunta: '¿Se puede congelar?', respuesta: 'Sí, en porciones individuales y bien envuelto.' },
    ],
    reviews: [
      { usuario: 'Marta V.', rating: 5, comentario: 'Esponjoso y con aroma a limón perfecto.' },
      { usuario: 'Ruben J.', rating: 4, comentario: 'Ideal para desayunar, muy suave.' },
    ],
  },
  {
    nombre: 'Salchichas alemanas con col y patata',
    descripcion: 'Plato contundente y muy reconfortante: salchichas doradas, col salteada y patata tierna con un toque de mostaza.',
    foto_url: '/img/recetas/salchichas_col.png',
    tiempo_minutos: 35,
    raciones_base: 3,
    semana_activa: '2026-07-07',
    dificultad: 'Media',
    categoria: 'Principal',
    calorias_racion: 720,
    autor_origen: 'Cocina Hacendado',
    cocina: 'Alemana',
    tags: [],
    ingredientes: [
      { producto: 'Patatas Hacendado', cantidad_base: 450, unidad: 'g', nombre_display: 'Patatas', grupo: 'Para la base' },
      { producto: 'Col blanca Hacendado', cantidad_base: 400, unidad: 'g', nombre_display: 'Col blanca', grupo: 'Para la base' },
      { producto: 'Cebolla Hacendado', cantidad_base: 90, unidad: 'g', nombre_display: 'Cebolla', grupo: 'Para la base' },
      { producto: 'Aceite de oliva virgen extra Hacendado', cantidad_base: 25, unidad: 'ml', nombre_display: 'Aceite', grupo: 'Para la base' },
      { producto: 'Sal marina Hacendado', cantidad_base: 4, unidad: 'g', nombre_display: 'Sal', grupo: 'Para la base' },
      { producto: 'Salchichas tipo Bratwurst Hacendado', cantidad_base: 360, unidad: 'g', nombre_display: 'Salchichas', grupo: 'Para la carne' },
      { producto: 'Pimienta negra molida Hacendado', cantidad_base: 2, unidad: 'g', nombre_display: 'Pimienta', grupo: 'Para la carne' },
      { producto: 'Mostaza suave Hacendado', cantidad_base: 40, unidad: 'g', nombre_display: 'Mostaza', grupo: 'Para el acabado' },
      { producto: 'Perejil fresco Hacendado', cantidad_base: 10, unidad: 'g', nombre_display: 'Perejil', grupo: 'Para el acabado' },
    ],
    pasos: [
      'Cuece las patatas en agua con sal 12-14 minutos, hasta que estén tiernas. Escurre y reserva.',
      'Saltea la cebolla y la col con el aceite 8-10 minutos, hasta que estén suaves y ligeramente doradas.',
      'Dora las salchichas en una sartén aparte hasta que estén bien hechas.',
      'Mezcla patata y col en la sartén principal, ajusta de sal y pimienta.',
      'Sirve con las salchichas encima, una cucharada de mostaza y perejil picado.',
    ],
    consejos: [
      'Corta la col muy fina para que se cocine de forma uniforme.',
      'Si quieres un toque más suave, añade un poco de agua al salteado.',
    ],
    faq: [
      { pregunta: '¿Puedo usar otra salchicha?', respuesta: 'Sí, cualquier salchicha fresca sirve; ajusta tiempos.' },
      { pregunta: '¿Se puede añadir manzana?', respuesta: 'Sí, aporta un contraste dulce muy típico.' },
    ],
    reviews: [
      { usuario: 'Daniela K.', rating: 5, comentario: 'Súper reconfortante, me recordó a Berlín.' },
      { usuario: 'Nacho P.', rating: 4, comentario: 'Buena combinación, la mostaza queda perfecta.' },
    ],
  },
];

module.exports = recetas;
